import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Search from './search'
import Works from './works'
import Waranty from './homeWaranty'
import Mobile from './mobile'

import ServiceTech from './serviceTech'
import Available from './available'
import Plan from './plan'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lybley</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='' >
      <Search />
      <Works />
      <Waranty />
      <ServiceTech />
      <Plan />
      <Mobile />
      <Available />
      </main>
    </>
  )
}
